//! `tungsten explain keywords` — which words the lexer reserves, and why that
//! is a question worth a command.
//!
//! ## Why this exists
//!
//! An identifier equal to a reserved word does not produce "`sym` is a
//! keyword". It produces `InvalidPattern` — reported at the token *after* the
//! offending word. So `fn f(sym: TreeSymbol)` underlines `TreeSymbol`, and a
//! reader with four such errors concludes the type is wrong. ADR 7.8.26b's
//! retrospective lost a round trip to exactly that, on `sym` (proof-term
//! symmetry), which is not a word anyone expects to be taken.
//!
//! The proof keywords are the trap in general: `by`, `have`, `show`, `sym`,
//! `cong`, `trans`, `subst` and `refl` are short, ordinary-looking English
//! words that read as perfectly good parameter names.
//!
//! ## One authority, machine-checked
//!
//! The keyword SET comes from [`ALL_KEYWORDS`], generated by the same macro
//! invocation the lexer's `keyword_from_str` is generated from
//! (`token/display.rs`) — so it cannot drift from what the lexer enforces.
//! Only the *grouping* lives here, and `tests::every_keyword_is_categorised`
//! asserts the two agree in both directions: a keyword added to the lexer and
//! not categorised here fails the build, as does a category entry naming a
//! word the lexer does not reserve.

use std::fmt::Write as _;

// Via the library path, not `crate::`: `explain` is compiled into the BIN,
// whose crate root has no `mod token`.
use tungsten_bootstrap::token::ALL_KEYWORDS;

/// One group of reserved words, with the reason they are reserved.
struct KeywordGroup {
    title: &'static str,
    note: &'static str,
    words: &'static [&'static str],
}

/// The grouping. Membership is asserted against [`ALL_KEYWORDS`] by the tests
/// below, so this list is total and non-overlapping by construction.
const GROUPS: &[KeywordGroup] = &[
    KeywordGroup {
        title: "Core",
        note: "the everyday language; nobody is surprised by these",
        words: &[
            "fn", "let", "if", "else", "match", "return", "try", "type", "struct", "enum", "true",
            "false",
        ],
    },
    KeywordGroup {
        title: "Proof",
        note: "THE TRAP — ordinary English words that read as good parameter names",
        words: &[
            "theorem", "lemma", "axiom", "by", "have", "show", "assume", "forall", "exists",
            "Prop", "sorry", "refl", "subst", "sym", "trans", "cong", "natind", "natrec",
        ],
    },
    KeywordGroup {
        title: "Type",
        note: "the primitive types; capitalised, so they collide with type names",
        words: &["Bool", "Nat", "Unit", "Void"],
    },
    KeywordGroup {
        title: "Module",
        note: "declaration and visibility",
        words: &["mod", "pub"],
    },
    KeywordGroup {
        title: "Reserved (unimplemented)",
        note: "taken by the lexer, not yet meaningful — kept free for later",
        words: &[
            "async", "await", "use", "impl", "trait", "where", "self", "Self", "mut", "ref",
            "move", "loop", "while", "for", "in", "break", "continue", "const", "static", "extern",
            "crate", "super", "dyn", "unsafe", "as",
        ],
    },
];

/// The group a reserved word belongs to, or `None` if it is not reserved.
#[must_use]
pub fn group_of(word: &str) -> Option<&'static str> {
    GROUPS
        .iter()
        .find(|g| g.words.contains(&word))
        .map(|g| g.title)
}

/// What to print for a single queried word.
///
/// Returned as a value rather than printed so the decision is testable
/// without capturing stdout — the reason it is an enum and not a `String` is
/// that the two cases have different exit codes, and a test asserting on
/// prose would pass on the wrong one.
#[derive(Debug, PartialEq, Eq)]
pub enum KeywordVerdict {
    /// Reserved, in this group. Cannot be used as an identifier.
    Reserved { group: &'static str },
    /// Not reserved — the name is available.
    Available,
}

/// Decide the verdict for one word. Pure.
#[must_use]
pub fn verdict(word: &str) -> KeywordVerdict {
    match group_of(word) {
        Some(group) => KeywordVerdict::Reserved { group },
        None => KeywordVerdict::Available,
    }
}

/// Render the whole catalogue, grouped.
#[must_use]
pub fn render_all() -> String {
    let mut out = String::from(
        "RESERVED WORDS\n\n\
         An identifier equal to any word below fails to PARSE. The error is\n\
         `InvalidPattern` or `expected item`, and it is reported at the token\n\
         AFTER the offending word — so `fn f(sym: T)` underlines `T`, not `sym`.\n\
         If a parse error points at something that looks fine, check the token\n\
         before it against this list.\n\n",
    );
    for group in GROUPS {
        let _ = writeln!(out, "{} — {}", group.title, group.note);
        let _ = writeln!(out, "  {}\n", group.words.join(" "));
    }
    let _ = writeln!(
        out,
        "{} reserved word(s).\n\n\
         Ask about one name:  tungsten explain keywords sym",
        ALL_KEYWORDS.len()
    );
    out
}

/// Render the answer for a single queried word.
#[must_use]
pub fn render_one(word: &str) -> String {
    match verdict(word) {
        KeywordVerdict::Reserved { group } => format!(
            "`{word}` is RESERVED ({group} keyword).\n\n\
             It cannot be used as an identifier. Using it produces a PARSE\n\
             error reported at the following token, not at `{word}` itself.\n"
        ),
        KeywordVerdict::Available => {
            format!("`{word}` is not reserved — it is available as an identifier.\n")
        }
    }
}

/// The whole command's output, as a value: no argument lists everything, an
/// argument queries one word.
///
/// **Returns a `String`, not an `ExitCode`, and the dispatch lives here rather
/// than in `cmd_explain`.** Both halves of that are forced. A
/// `-> ExitCode` wrapper would be *unkillable* — the body can only return
/// `ExitCode::SUCCESS`, and `ExitCode::default()` is also 0, so cargo-mutants'
/// `-> Default::default()` mutant is observationally equivalent and survives
/// forever. Putting the `match` in `cmd_explain` instead trades that for a
/// match-depth-2 violation, since that function is already one `match` deep.
/// A `String`-returning function one level down is neither: mutable,
/// assertable, and flat at the call site.
#[must_use]
pub fn render(word: Option<&str>) -> String {
    match word {
        None => render_all(),
        Some(w) => render_one(w),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    /// The grouping is TOTAL over what the lexer reserves, in both directions.
    ///
    /// This is the whole point of the file: a keyword added to
    /// `token/display.rs` and not categorised here fails the build rather than
    /// quietly vanishing from the explainer's output — which is the failure
    /// mode a hand-transcribed list has, and the one ADR 13.8.26a exists to
    /// stop repeating.
    #[test]
    fn every_keyword_is_categorised() {
        let lexer: HashSet<&str> = ALL_KEYWORDS.iter().copied().collect();
        let grouped: HashSet<&str> = GROUPS
            .iter()
            .flat_map(|g| g.words.iter().copied())
            .collect();

        let uncategorised: Vec<_> = lexer.difference(&grouped).copied().collect();
        assert!(
            uncategorised.is_empty(),
            "reserved by the lexer but missing from GROUPS: {uncategorised:?}"
        );

        let invented: Vec<_> = grouped.difference(&lexer).copied().collect();
        assert!(
            invented.is_empty(),
            "in GROUPS but NOT reserved by the lexer: {invented:?}"
        );
    }

    /// No word appears in two groups — otherwise `group_of` would report
    /// whichever came first and the counts below would double-count.
    #[test]
    fn groups_do_not_overlap() {
        let mut seen = HashSet::new();
        for group in GROUPS {
            for word in group.words {
                assert!(seen.insert(*word), "`{word}` appears in two groups");
            }
        }
        assert_eq!(seen.len(), ALL_KEYWORDS.len());
    }

    /// The word that motivated the command, and its neighbours.
    #[test]
    fn proof_keywords_are_reserved() {
        for word in [
            "sym", "by", "have", "show", "cong", "trans", "subst", "refl",
        ] {
            assert_eq!(
                verdict(word),
                KeywordVerdict::Reserved { group: "Proof" },
                "`{word}` should be a reserved proof keyword"
            );
        }
    }

    /// Ordinary identifiers are NOT reported as reserved.
    ///
    /// Without this, a `verdict` that answered `Reserved` for everything would
    /// satisfy the test above — the inverse is what makes it mean anything.
    #[test]
    fn ordinary_identifiers_are_available() {
        for word in ["symbol", "symmetry", "by_ref", "haved", "test_begin", ""] {
            assert_eq!(
                verdict(word),
                KeywordVerdict::Available,
                "`{word}` should be available"
            );
        }
    }

    /// The rendered listing names every reserved word and states the count.
    #[test]
    fn render_all_covers_every_keyword() {
        let rendered = render_all();
        for word in ALL_KEYWORDS {
            assert!(
                rendered.contains(word),
                "`{word}` missing from the rendered catalogue"
            );
        }
        assert!(rendered.contains(&format!("{} reserved word(s)", ALL_KEYWORDS.len())));
    }

    /// `render` dispatches on presence, and both branches reach real output.
    ///
    /// Without this the `Option` arm is untested and a mutant swapping the two
    /// branches survives — the listing and the single-word answer are both
    /// non-empty, so only their CONTENT distinguishes them.
    #[test]
    fn render_dispatches_on_the_argument() {
        assert!(render(None).contains("RESERVED WORDS"));
        assert!(render(None).contains("reserved word(s)"));
        assert!(render(Some("sym")).contains("is RESERVED (Proof keyword)"));
        assert!(!render(Some("sym")).contains("RESERVED WORDS"));
        assert!(render(Some("symbol")).contains("not reserved"));
    }

    /// The single-word rendering distinguishes its two cases.
    #[test]
    fn render_one_distinguishes_reserved_from_available() {
        assert!(render_one("sym").contains("RESERVED"));
        assert!(render_one("sym").contains("Proof"));
        assert!(render_one("symbol").contains("not reserved"));
        assert!(!render_one("symbol").contains("RESERVED"));
    }
}
