//! `tungsten info try-desugar`: show `?` operator desugaring for a definition.

use std::path::PathBuf;
use std::process::ExitCode;

use tungsten_core::Term;

use crate::info::elaborate_for_info;
use crate::info::helpers::format_semantic_type;
/// Show how `?` operators in a definition were desugared to Core IR.
///
/// Finds case expressions with `__try_err`/`__try_ok` binders (the internal
/// names generated by `elab_try`) and displays each one with its structure.
pub fn cmd_info_try_desugar(
    name: &str,
    file: &PathBuf,
    verbose: bool,
    max_errors: usize,
) -> ExitCode {
    let Some(project) = elaborate_for_info(file, verbose, max_errors) else {
        return ExitCode::FAILURE;
    };

    let Some(def) = project.defs.iter().find(|d| d.name == name) else {
        eprintln!("Definition not found: {name}");
        return ExitCode::FAILURE;
    };

    let semantic = format_semantic_type(&def.ty, &project.type_provenance);
    let structural = format!("{}", def.ty);
    let type_str = if let Some(sem) = &semantic {
        sem.as_str()
    } else {
        &structural
    };

    println!("Definition: {name}");
    println!("Type:       {type_str}");
    println!();

    let desugars = collect_try_desugars(&def.term);

    if desugars.is_empty() {
        println!("No `?` operator desugaring found in this definition.");
        return ExitCode::SUCCESS;
    }

    println!(
        "Found {} `?` desugaring{}:",
        desugars.len(),
        if desugars.len() == 1 { "" } else { "s" }
    );
    println!();

    for (i, desugar) in desugars.iter().enumerate() {
        println!("  {}. {}", i + 1, desugar.description);
        println!("     scrutinee: {}", desugar.scrutinee);
        println!("     error branch: return {}", desugar.error_body);
        println!("     success: {}", desugar.success_var);
        println!();
    }

    ExitCode::SUCCESS
}

/// A single `?` desugaring found in a Core term.
struct TryDesugar {
    description: String,
    scrutinee: String,
    error_body: String,
    success_var: String,
}

/// Walk a Core term and collect all `?` desugaring patterns.
///
/// The pattern is: `case(scrutinee, "__try_err", error_body, "__try_ok", success)`
/// where `error_body` contains a `Return(Inl(...))`.
fn collect_try_desugars(term: &Term) -> Vec<TryDesugar> {
    let mut results = Vec::new();
    walk_for_try(term, &mut results);
    results
}

fn walk_for_try(term: &Term, results: &mut Vec<TryDesugar>) {
    match term {
        Term::Case(scrutinee, left_var, left_body, right_var, right_body) => {
            if left_var == "__try_err" && right_var == "__try_ok" {
                let kind = if contains_return_unit(left_body) {
                    "Option?"
                } else {
                    "Result?"
                };
                results.push(TryDesugar {
                    description: format!("{kind} desugaring"),
                    scrutinee: format!("{scrutinee}"),
                    error_body: format_error_body(left_body),
                    success_var: right_var.clone(),
                });
            }
            // Recurse into sub-terms (there may be nested `?`)
            walk_for_try(scrutinee, results);
            walk_for_try(left_body, results);
            walk_for_try(right_body, results);
        }
        // Recurse into all term constructors that can contain sub-terms
        Term::Lambda(_, _, body) => walk_for_try(body, results),
        Term::App(f, arg) => {
            walk_for_try(f, results);
            walk_for_try(arg, results);
        }
        Term::Let(_, _, val, body) => {
            walk_for_try(val, results);
            walk_for_try(body, results);
        }
        Term::Succ(t) => walk_for_try(t, results),
        Term::Inl(_, t) | Term::Inr(_, t) => walk_for_try(t, results),
        Term::Fold(_, t) | Term::Unfold(_, t) => walk_for_try(t, results),
        Term::Return(t) => walk_for_try(t, results),
        Term::Pair(a, b) => {
            walk_for_try(a, results);
            walk_for_try(b, results);
        }
        Term::Fst(t) | Term::Snd(t) => walk_for_try(t, results),
        Term::NatRec(_, z, s, n) => {
            walk_for_try(z, results);
            walk_for_try(s, results);
            walk_for_try(n, results);
        }
        _ => {}
    }
}

/// Check if the error body injects Unit (Option? pattern).
fn contains_return_unit(term: &Term) -> bool {
    match term {
        Term::Return(inner) => contains_inl_unit(inner),
        Term::Fold(_, inner) => contains_return_unit(inner),
        _ => false,
    }
}

fn contains_inl_unit(term: &Term) -> bool {
    match term {
        Term::Inl(_, inner) => matches!(**inner, Term::Unit),
        Term::Fold(_, inner) => contains_inl_unit(inner),
        _ => false,
    }
}

/// Format the error body for display (simplified).
fn format_error_body(term: &Term) -> String {
    format!("{term}")
}
